---

# These 2 tasks add the subnet to the routing table based on
# the route_table tag of the subnet. This tag is the name
# of the routing table to add the subnet to. From the name we can
# lookup the ID.

- name: create dict of route table id's
  set_fact:
     add_table: "{{ add_table|default({}) | combine ({ item.tags.Name: { 'id': item.id } }) }}"
  with_items:
    - "{{ ec2_table.route_tables }}"
  loop_control:
    label: "{{ item.tags.Name }}"

- name: add subnets to route table
  ec2_vpc_route_table:
    region: "{{ region }}"
    vpc_id: "{{ vpc_id }}"
    state: present
    purge_subnets: false
    purge_routes: false
    lookup: id
    route_table_id: "{{ add_table[item.subnet.tags.route_table].id }}"
    subnets:
      - "{{ item.subnet.id }}"
  with_items:
    - "{{ new_subnets.results }}"
  loop_control:
    label: "{{ item.subnet.id }} {{ item.subnet.tags.route_table }}"
