---
# tasks file for ec2-subnets

- include_tasks: vpc-route-table.yml
- include_tasks: subnets.yml
  when: vpc_subnets is defined
- include_tasks: add-to-route-table.yml
  when: add_route_table is defined
